name: Websever release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v4

    - name: 'gosec'
      uses: securego/gosec@master
      with:   
        args: -exclude=G104 ./...

    - name: 'golangci-lint'
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
        args: -D errcheck

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up Go'
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: 'Install dependencies'
      run: |
        go get .

    - name: 'Build'
      run: go build -o challenge -v main.go 

    - name: 'Upload binary'
      uses: actions/upload-artifact@v4
      with:
        name: webserver
        path: challenge
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [test,build]
    steps:
    - uses: actions/checkout@v4

    - name: 'Download webserver binary'
      uses: actions/download-artifact@v4
      with:
        name: webserver

    - name: 'Release'
      uses: softprops/action-gh-release@v2
      with:
        files: challenge
        token: ${{ secrets.PAT }}
